home-assistant/cli

- .travis.yml
- commands.go
- version.go
Added some linting to catch some stylistic errors
> Add linter travis

- main.go
As part of official home-assistant project, we use the same infos like the other official stuff.
> Update maintainer infos

- .hound.yml
- .travis.yml
- CHANGELOG.md
- README.md
- command/helpers/common.go
- command/helpers/common_test.go
- command/homeassistant.go
- command/host.go
- command/network.go
- command/network_test.go
- command/supervisor.go
- commands.go
- main.go
- version.go
First release of the hassio CLI written in GO
> Release 1.0.0

- command/helpers/common.go
XHASSIOKEY was implemented incorrectly. This corrects it
> Fix for XHASSIOKEY

- command/helpers/common.go
- command/helpers/common_test.go
- `export HASSIO=""`
- `export HASSIO="example.com"`
> Added ability to override the server

- README.md
- command/helpers/common.go
- command/snapshots.go
- command/snapshots_test.go
- commands.go
I've tested
* list
* info
* new
* remove
Untested:
* restore
Only supporting FULL snapshots in this release
Could someone please test restore for me?
> Snapshot support

- README.md
- command/addons.go
- command/addons_test.go
- command/snapshots.go
- commands.go
*Untested* as currently mobile without access to hass.io
> Addon subcommand and switch rename

- .travis.yml
https://www.alexruf.net/2016/01/16/cross-compile-with-go-1-5-for-raspberry-pi.html
> Bugfix arm builds

- command/helpers/common.go
- version.go
* Fix to output error to STDERR
> Release 1.2.1

- command/snapshots.go
- commands.go
Added password & user options for snapshot create & restore
Fixed snapshots to take -slug option instead of -name
@pvizeli Would you be able to give this code a quick test please?
> Added Features for snapshots and changed misleading param

- command/hardware.go
Fixes: https://github.com/home-assistant/hassio-cli/issues/72
> Fixed 405 Error for hardware/<info|audio> (#72)

- README.md
- command/hardware.go
- version.go
Fixes: https://github.com/home-assistant/hassio-cli/issues/72
Updated README
> Release 1.3.1

- command/helpers/common.go
https://github.com/home-assistant/hassio-cli/issues/87
> Fix error output end in a trace

- README.md
I've removed some stuff from the README to make it less bloated, and less maintenance.
Also a lot of Markdown styling fixes.
> Updates and simplifies README

- .travis.yml
- command/helpers/common.go
- command/helpers/common_test.go
The golint call didn't check all folders, while fixing this it started to complain about exported function.
So i unexported the function because they didn't need it
this also fixes the build issue with golint which refuses to compile in the default go compiler under travis/trusty
> Fix travis issues and resulting golint errors

- cmd/hassos_update.go
The problem is, it gives to HassOS update. One for OS and another for CLI. For now we can handle the OS update command.
> HassOS update

- .travis.yml
Adds support for ARMv7 builds, which we are going to support in the very near future.
> ✨Adds build for ARMv7

- cmd/homeassistant_rebuild.go
For: https://github.com/home-assistant/hassio/pull/808
> Add homeassistant rebuild command

- .travis.yml
Updates Golang to 1.12
Also updates the download location for golint.
> Updates Golang to 1.12 & golint

- cmd/hassos_import.go
Add support for the HassOS import/sync command.
> Adds HassOS import command

- cmd/hassos_update_cli.go
Adds support for updating the HassOS CLI
> Adds HassOS update CLI command

- cmd/completion.go
- cmd/root.go
2 Minor tweaks to textual things inside the codebase
> Small tweak to textual contents

- README.md
thought it would be useful to document how to run this standalone/remotely.
> document how to run hassio-cli remotely

- .travis.yml
This PR removes a duplicate env entry in the travis ci file
> Removes duplicate env setting in TravisCI file

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Adds a Remote Development Container for use with Visual Studio Code
> Adds VSCode remote devcontainer

- cmd/dns.go
- cmd/dns_info.go
- cmd/dns_logs.go
- cmd/dns_options.go
- cmd/dns_stats.go
- cmd/dns_update.go
Adds support for DNS commands, introduced by home-assistant/hassio#1195
> Adds support for DNS commands

- cmd/dns_restart.go
Add support for the DNS restart API endpoint.
`hassio dns restart`
> Add dns restart command

- cmd/dns_reset.go
closes #188
awaits <https://github.com/home-assistant/hassio-supervisor/pull/1428>
> Add reset command to Hass.io DNS

- cmd/audio_profile.go
Fix the parameters of the audio profile command.
> Fix audio profile command

- README.md
- cmd/root.go
Use the details from the code but add a little formatting for easier reading.
> Use same details as in the code

- cmd/network_update.go
> Fix network interface update

- README.md
Updated the available commands in the README
> Update available commands

- client/client.go
> Print status code if unexpected response is received

- cmd/banner.go
During startup the API might not return data. In this case pokeAPI
returns nil. Handle this error cases properly.
> Improve error handling when showing banner

- client/client.go
- client/helper.go
- cmd/addons_rebuild.go
- cmd/audio_update.go
- cmd/cli_update.go
- cmd/core_check.go
- cmd/core_rebuild.go
- cmd/core_update.go
- cmd/dns_update.go
- cmd/multicast_update.go
- cmd/observer_update.go
- cmd/os_update.go
- cmd/snapshots_new.go
- cmd/snapshots_restore.go
- cmd/supervisor_update.go
> Customize timeouts for some commands

- cmd/backups_restore.go
The flag is `--addons` not `--addon`
> Fix backups_restore example

- cmd/core.go
It's now a while ago that HA had 0.X releases.
> Update version sample to a stable version

- cmd/available_updates.go
- cmd/refresh_updates.go
For https://github.com/home-assistant/supervisor/pull/3413
> Add new root endpoints

- cmd/supervisor_options.go
Add support for changing supervisor auto update for https://github.com/home-assistant/supervisor/pull/3769
> Add supervisor auto update option

- cmd/resolution_issue_suggestions.go
Add new API added in https://github.com/home-assistant/supervisor/pull/3818
> Add issue suggestions API to CLI

- cmd/backups.go
- cmd/backups_options.go
Add new option added in https://github.com/home-assistant/supervisor/pull/3814 to CLI
> Add backup manager options to cli

- cmd/resolution_check.go
- cmd/resolution_check_options.go
- cmd/resolution_check_run.go
- cmd/resolution_issue.go
- cmd/resolution_issue_dismiss.go
- cmd/resolution_issue_suggestions.go
- cmd/resolution_suggestion.go
- cmd/resolution_suggestion_apply.go
- cmd/resolution_suggestion_dismiss.go
- cmd/root.go
See individual commits for details.
> Add more completions

- cmd/mounts.go
- cmd/mounts_add.go
- cmd/mounts_delete.go
- cmd/mounts_info.go
- cmd/mounts_reload.go
- cmd/mounts_update.go
CLI support for new APIs added in https://github.com/home-assistant/supervisor/pull/4269
> Add mounts commands for network share support

- cmd/mounts.go
> Only one parameter uses u shorthand

- cmd/mounts.go
- cmd/mounts_info.go
> Fix double h shorthand

- cmd/backups.go
- cmd/backups_new.go
- cmd/mounts.go
- cmd/mounts_delete.go
- cmd/mounts_options.go
- cmd/mounts_reload.go
- cmd/mounts_update.go
Add support for new option to specify a mount to use for backup. Also add some completions around mounts. Corresponding supervisor PR: https://github.com/home-assistant/supervisor/pull/4289
> Add backup location support and completions

- cmd/mounts.go
For https://github.com/home-assistant/supervisor/pull/4395
> Add flag for CIFS version

- cmd/backups_new.go
- cmd/core_options.go
CLI support for changes in https://github.com/home-assistant/supervisor/pull/4591
> Add exclude DB options to CLI

- .github/workflows/golangci-lint.yml
- .golangci.yaml
- cmd/host_logs_boots.go
- cmd/host_logs_identifiers.go
So that the config applies to local runs too, not just in CI.
> Configure golangci-lint using config file, enable some more linters

- cmd/network_update.go
Fixes #404
Just a typo that stopped this flag from working properly
> Fix network update nameservers flag

- .golangci.yaml
- client/helper.go
- cmd/audio_volume.go
- cmd/backups_new.go
- cmd/core_options.go
- cmd/mounts.go
- cmd/os_boards_green_options.go
- cmd/os_boards_yellow_options.go
- cmd/security_options.go
- cmd/supervisor_options.go
See individual commits for details.
> More linting, address findings, config improvements

- cmd/backups_options.go
> Fixes a misnamed "days_until_stale" in backup options.

- cmd/mounts.go
> Remove shorthand for read-only mounts

- cmd/addons_uninstall.go
CLI support for https://github.com/home-assistant/supervisor/pull/4913
> Allow removing addon config on uninstall

- cmd/core_restart.go
CLI support for https://github.com/home-assistant/supervisor/pull/5017
> Allow restarting core in safe mode
