- .travis.yml
Adds automatic creation of binaries for hassio-cli to releases.
Just apply tag (should match version number in version.go) and push travis should do the rest
> Added autodeploy to travis

- command/helpers/common.go
Labelled as breaking as now ok with NO data just returns "ok" and error messages are no longer processed as json.
To get guaranteed json output --rawjson is now required.
> Tidied output when error is detected

- command/helpers/common.go
- commands.go
- version.go
* Output cleanup -> This may break scripts that depended on default output being json, this was a by product historically. The only _supported_ way to get json is to use --rawjson
* Fixed shortnames for commands to be consistant -> This will break scripts using shortnames in some instances. Shortnames are *not* supported for scripting use the full command name in scripts, short forms are there purely for the user at the cli.
> Release 1.2

- .travis.yml
This fixes #114 
Also added golang 1.11 because it is the latest release, if that is an issue, i'll drop the commit
> Remove deprecated golang 1.6

- command/addons.go
- command/hardware.go
- command/hassos.go
- command/helpers/common.go
- command/homeassistant.go
- command/host.go
- command/snapshots.go
- command/supervisor.go
- commands.go
- main.go
Fix for #110 
This is an initial change to convert the Printf bases logoutput to logrus. With as end goal the ability to use the cli with json logging format for easier integration in other tools. For step 1 i converted all the debug statements. 
Further work:
- move errors to logrus as well, insteda of the fprintf
> Replace log output with logger

- cmd/root.go
This fixes #140 by looking at the name of the binary used to invoke the
cli.
as side effect, the completion and help contain the whatever used to
invoke the binary, using go run for example with use the name `main`
> Take binary name from running command instead of hardcoded value

- cmd/supervisor_options.go
Currently, the CLI sends in an empty add-on repository array on changing supervisor options (without specifying repository flags).
This works around that issue by requiring at least one repositories argument before the array is sent to the API.
> Only set add-on repositories when at least 1 is given

- cmd/completion.go
Currently, the CLI supports generating a Bash completion script. This also works for ZSH, however, Cobra is also capable of a more compatible/specific completion script for ZSH.
This PR adds that capability by introducing an additional flag.
For Bash: `hassio completion`
For ZSH:  `hassio completion --zsh`
> Adds support for generating ZSH completion script

- client/helper.go
- cmd/addons_install.go
- cmd/addons_rebuild.go
- cmd/addons_reload.go
- cmd/addons_update.go
- cmd/dns_update.go
- cmd/hassos_update.go
- cmd/hassos_update_cli.go
- cmd/homeassistant_check.go
- cmd/homeassistant_rebuild.go
- cmd/homeassistant_restart.go
- cmd/homeassistant_start.go
- cmd/homeassistant_stop.go
- cmd/homeassistant_update.go
- cmd/root.go
- cmd/snapshots_new.go
- cmd/snapshots_restore.go
- cmd/supervisor_repair.go
- cmd/supervisor_update.go
- go.mod
- go.sum
- Adds a little spinner, to show we are busy.
* Spinner is written to StdErr, so the redirected output is not affected
* Spinner writes to a nulled buffer when not in TTY
* Adds `--no-progress` global flag, to force disable spinner
* Spinner is only added to commands that are known to take a little longer (e.g. update, install, new snapshots)
- Instead of a simple "ok" message, I've replaced the success message with the more friendly: "Command completed successfully."
> Adds processing spinner and improves command completed message

- cmd/root.go
- go.mod
- go.sum
- spinner/character_sets.go
- spinner/spinner.go
Fixes #179 
Added own version of the Spinner. Slimmed it down in the process.
> Fix progress spinner on Putty

- cmd/completion.go
Fixes ZSH completion script.
The completion script generated by the Cobra library is missing a compdef at the end of the script.
This adds in a workaround that outputs the missing compdef after Cobra has generated it.
> Fix ZSH completion

- cmd/snapshots_new.go
Fixed issue where attempting to do a partial snapshot with just addons specified would always do a full snapshot.
> Fixed partial snapshot issue

- cmd/auth.go
- cmd/auth_reset.go
Adds support for the new Home Assistant password reset command.
Closes #189
Please note, while this command seems to be working fine, the Supervisor seems to have an issue with the password reset.
> Add Home Assistant password reset commands

- cmd/core.go
- cmd/os.go
The `PersistentPreRun` on commands does not bubble up to parent commands.
For the `os` and `core` commands have their own, this PR makes sure the parent command (rootCmd) is also executed.
This fixes things like the ProgressSpinner.
> Fix execution of rootCmd PreRun

- cmd/core.go
- cmd/os.go
- The order of the `PersistantPreRun` could mess with the Spinner (the spinner could overwrite the deprecation message because of timing in a terminal).
- The new CLI command is `ha`, but `ha` is also deprecated as sub-command. I've adjusted the deprecation logic to be able to handle that.
> Fix spinner overwrite and deprecation false-positive

- cmd/auth_reset.go
Adds an additional output message when auth reset fails when the used API token doesn't work.
Closes #204
> Print addition error message on failed auth reset

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
This PR adds clarity on how to use this tool, how to install it and make a better separation between the user use case and development use case.
Furthermore, and issue in the issue template has been addressed, which asks for a version with a command line that originates from the origin Bash based version from a long long time ago.
Closes #213
> Update README and issue template to remove legacy and add clarity

- cmd/addons_info.go
fixes #217 
`ha addon info` would not work and required an argument (add-on slug).
Changed this behavior to use the default of `self` as the slug when the add-on slug isn't specified.
> Default to self for addon info command

- cmd/snapshots_new.go
I noticed that the snapshot example (help command) does not work and is therefore misleading. The folder has to be called "homeassistant" instead of "config".
> Fix snapshot example string

- cmd/network_scan.go
- cmd/network_update.go
- cmd/network_vlan.go
> New Network API

- cmd/banner.go
This allows to print a banner with some useful information about the
Home Assistant system, e.g.:
```
| |  | |                          /\           (_)   | |            | |
| |__| | ___  _ __ ___   ___     /  \   ___ ___ _ ___| |_ __ _ _ __ | |_
|  __  |/ _ \| '_ \ _ \\ / _ \   / /\ \ / __/ __| / __| __/ _\ | '_ \| __|
| |  | | (_) | | | | | |  __/  / ____ \\__ \__ \ \__ \ || (_| | | | | |_
|_|  |_|\___/|_| |_| |_|\___| /_/    \_\___/___/_|___/\__\__,_|_| |_|\__|
Welcome to the Home Assistant command line.
System information
IPv4 addresss for eno1:   192.168.80.107/24
Operating System Version: HassOS 5.6.dev20201127
Home Assistant Core:      0.118.4
Internal URL:             http://ha-intel-nuc:8123
For more details use 'help' and 'exit' to close.
If you need access to host system use …
```
> Add banner subcommand

- cmd/banner.go
Don't dereference interfaces if no network information have been
returned.
> Check if networking information have been returned

- cmd/banner.go
At startup, the Supervisor API returns an error with the message that
the Supervisor is still in setup. This leads to an empty banner, which
is not that helpful. Wait by default until the Supervisor returns useful
data.
> Wait until Supervisor has been started before printing the banner

- client/helper.go
- cmd/addons_install.go
- cmd/addons_rebuild.go
- cmd/addons_restart.go
- cmd/addons_stop.go
- cmd/addons_uninstall.go
- cmd/core_rebuild.go
- cmd/core_restart.go
- cmd/core_start.go
- cmd/core_stop.go
- cmd/core_update.go
- cmd/multicast_restart.go
- cmd/multicast_update.go
- cmd/observer_update.go
- cmd/snapshots_new.go
- cmd/snapshots_restore.go
- cmd/supervisor_repair.go
- cmd/supervisor_restart.go
- cmd/supervisor_update.go
Centralize timeout default values in helper. Increase timeouts related
to Container operations such as start/stop/restart commands.
Fixes: #297, #298
> Increase timeouts for start/stop/restart commands

- README.md
- client/helper.go
- cmd/backups.go
- cmd/backups_info.go
- cmd/backups_new.go
- cmd/backups_reload.go
- cmd/backups_remove.go
- cmd/backups_restore.go
Rename "snapshot" to "backup"
Related:
<https://github.com/home-assistant/core/pull/51629>
<https://github.com/home-assistant/supervisor/pull/2940>
<https://github.com/home-assistant/frontend/pull/9393>
<https://github.com/home-assistant/my.home-assistant.io/pull/95>
<https://github.com/home-assistant/home-assistant.io/pull/18129>
<https://github.com/home-assistant/developers.home-assistant/pull/963>
<https://github.com/home-assistant/addons/pull/2088>
> Rename snapshot -> backup

- cmd/audio.go
The text "ha audio info" had a trailing " that was not needed and looked out of place.
Remove it as it is not necessary.
> audio: remove trailing " from help example

- client/helper.go
- cmd/audio_restart.go
- cmd/audio_update.go
- cmd/cli_update.go
- cmd/core_check.go
- cmd/dns_restart.go
- cmd/dns_update.go
- cmd/os_update.go
This replaces hard coded timeouts with an equal const value from the
helper module. All values remain the same except for core check comand,
which now uses a 10 minute timeout instead of 1 hour
(ContainerOperationTimeout).
> Use consts for timeouts in all cases

- cmd/core_options.go
Remove options which no longer exist and add newly added options. Also
make it possible to clear string settings by using an empty string ("")
which gets translated to null.
Related-to: https://github.com/home-assistant/developers.home-assistant/pull/1146
> Revamp ha core options subcommand

- cmd/dns_options.go
Adds option to disable the fallback DNS to leverage new API option.
Supervisor parent PR https://github.com/home-assistant/supervisor/pull/3586
> Add disable fallback dns option to CLI

- cmd/network_update.go
The `--enabled` option doesn't make sense if it's true by default and it can't be set to false. Turning it into a `--disabled` makes it so you can actually disable an interface. Fixes #333.
> Allow disabling network interface

- cmd/backups_new.go
Backups can be optionally uncompressed so provide command line flags to
request that.
Related to: https://github.com/home-assistant/supervisor/pull/3378
> backups_new: Add --compressed / --uncompressed flags

- cmd/store.go
- cmd/store_repositories_add.go
- cmd/store_repositories_delete.go
Add options for adding and removing a repository to store section.
Parent Supervisor PR: https://github.com/home-assistant/supervisor/pull/3649
> Add store add/remove APIs to CLI

- cmd/os_boards.go
- cmd/os_boards_yellow.go
- cmd/os_boards_yellow_options.go
Add boards commands to the CLI for APIs added to supervisor in https://github.com/home-assistant/supervisor/pull/3984 (and being updated in https://github.com/home-assistant/supervisor/pull/3990).
> Add boards commds

- cmd/backups_restore.go
To restore only HA core, `--folders homeassistant` is the correct command, not `--folders config`
See supervisor backup manager: https://github.com/home-assistant/supervisor/blob/main/supervisor/backups/manager.py#L387
```
if FOLDER_HOMEASSISTANT in folder_list:
folder_list.remove(FOLDER_HOMEASSISTANT)
homeassistant = True
```
> Fix restore example

- client/helper.go
- spinner/spinner.go
The [io/ioutil](https://tip.golang.org/pkg/io/ioutil/) was deprecated in Go 1.16.
https://tip.golang.org/doc/go1.16#ioutil
> Fix io/ioutil deprecation warnings

- cmd/mounts.go
Include share as mount usage option as per https://github.com/home-assistant/supervisor/pull/4318
> Include share as mount usage option

- cmd/backups_freeze.go
- cmd/backups_thaw.go
Add CLI for new freeze and thaw APIs created for external backups/snapshots in https://github.com/home-assistant/supervisor/pull/4538
> Add freeze/thaw apis to cli

- cmd/os_boards_green.go
- cmd/os_boards_green_options.go
Add CLI support for the new APIs to set LEDs on Green added in https://github.com/home-assistant/supervisor/pull/4556
> Add CLI support for new Green LED APIs

- .github/workflows/build.yml
This PR removes Codenotary. It is defunct and cause the previous release to fail.
Ref: <https://github.com/home-assistant/cli/actions/runs/6349283515>
> Remove defunct CAS

- .github/workflows/codespell.yml
- cmd/mounts.go
- cmd/mounts_add.go
Add support for making read-only mounts. CLI support for https://github.com/home-assistant/supervisor/pull/4872
Also have codespell ignore go.sum since its generated, it was throwing an error.
> Add support for making read-only mounts

- cmd/backups_new.go
Replica of #457, but for `homeassistant-exclude-database`. See https://github.com/home-assistant/cli/issues/457#issuecomment-1942474696
> Fix a misnamed `homeassistant-exclude-database`

- cmd/auth_list.go
CLI support for https://github.com/home-assistant/supervisor/pull/4912
> Allow listing of HA users via admin CLI

- cmd/addons_update.go
Use default container download timeout for add-on updates.
Fixes: #418
> Increase timeout for add-on updates

- client/helper.go
- cmd/os_datadisk_wipe.go
Add device wipe command to leverage new API in https://github.com/home-assistant/supervisor/pull/4934
As this command is quite destructive, it requires user confirmation to proceed.
> Add device wipe command to CLI

- cmd/host.go
With #471 the argument type changed to unsigned. This requires also a change when getting the value. We still need to convert the number to a signed integer since we need to pass a negative number as range header (to request the last x number of lines).
> Fix number of lines argument
